import 'package:flutter/widgets.dart';

enum AppLanguage {
  english('en', 'English'),
  malay('ms', 'Bahasa Melayu'),
  simplifiedChinese('zh_CN', '中文（简体）'),
  traditionalChinese('zh_TW', '中文（繁體）'),
  japanese('ja', '日本語'),
  korean('ko', '한국어'),
  spanish('es', 'Español'),
  french('fr', 'Français'),
  italian('it', 'Italiano'),
  german('de', 'Deutsch'),
  thai('th', 'ไทย'),
  hindi('hi', 'हिन्दी'),
  arabic('ar', 'العربية');

  const AppLanguage(this.code, this.label);
  final String code;
  final String label;

  Locale get locale {
    final parts = code.split('_');
    return parts.length == 2 ? Locale(parts[0], parts[1]) : Locale(code);
  }

  static AppLanguage fromCode(String? code) {
    final normalizedCode = code == 'zh' ? 'zh_CN' : code;
    return values.firstWhere(
      (language) => language.code == normalizedCode,
      orElse: () => AppLanguage.english,
    );
  }
}

class AppStrings {
  const AppStrings(this.language);
  final AppLanguage language;

  String t(String key) =>
      _translations[language.code]?[key] ?? _translations['en']![key] ?? key;

  String colorName(String englishName) => t('color.$englishName');
}

const _translations = <String, Map<String, String>>{
  'en': {
    'tagline': 'Helping colorblind users distinguish colors better.',
    'onboarding.enhance.title': 'Enhance color differences',
    'onboarding.enhance.text':
        'Apply assistive filters to photos when colors are difficult to tell apart.',
    'onboarding.identify.title': 'Identify colors around you',
    'onboarding.identify.text':
        'Use the camera to check a color name and its hex code in real time.',
    'onboarding.understand.title': 'Understand color vision',
    'onboarding.understand.text':
        'Preview simulations that show how color vision differences can appear.',
    'getStarted': 'Get Started',
    'tab.assist': 'Assist',
    'tab.detect': 'Detect',
    'tab.simulate': 'Simulate',
    'tab.settings': 'Settings',
    'appearance': 'Appearance',
    'darkMode': 'Dark mode',
    'darkEnabled': 'Dark theme enabled',
    'lightEnabled': 'Light theme enabled',
    'language': 'Language',
    'legal': 'Legal',
    'privacyPolicy': 'Privacy Policy',
    'termsOfUse': 'Terms of Use',
    'about': 'About',
    'appName': 'App Name',
    'appVersion': 'App Version',
    'linkError': 'Unable to open the link. Please try again.',
    'original': 'Original',
    'assistFilters': 'Assist filters',
    'takePhoto': 'Take Photo',
    'uploadPhoto': 'Upload Photo',
    'reset': 'Reset',
    'normal': 'Normal',
    'startingCamera': 'Starting camera...',
    'cameraUnavailable':
        'Camera unavailable. Check camera permission and try again.',
    'color.Black': 'Black',
    'color.White': 'White',
    'color.Gray': 'Gray',
    'color.Red': 'Red',
    'color.Orange': 'Orange',
    'color.Yellow': 'Yellow',
    'color.Green': 'Green',
    'color.Teal': 'Teal',
    'color.Blue': 'Blue',
    'color.Purple': 'Purple',
    'color.Pink': 'Pink',
    'color.Brown': 'Brown',
    'color.Charcoal': 'Charcoal',
    'color.Silver': 'Silver',
    'color.Maroon': 'Maroon',
    'color.Coral': 'Coral',
    'color.Gold': 'Gold',
    'color.Olive': 'Olive',
    'color.Lime': 'Lime',
    'color.Forest Green': 'Forest Green',
    'color.Mint': 'Mint',
    'color.Cyan': 'Cyan',
    'color.Sky Blue': 'Sky Blue',
    'color.Navy': 'Navy',
    'color.Indigo': 'Indigo',
    'color.Lavender': 'Lavender',
    'color.Magenta': 'Magenta',
    'color.Beige': 'Beige',
  },
  'ms': {
    'tagline':
        'Membantu pengguna buta warna membezakan warna dengan lebih baik.',
    'onboarding.enhance.title': 'Jelaskan perbezaan warna',
    'onboarding.enhance.text':
        'Gunakan penapis bantuan pada foto apabila warna sukar dibezakan.',
    'onboarding.identify.title': 'Kenal pasti warna di sekeliling',
    'onboarding.identify.text':
        'Gunakan kamera untuk menyemak nama warna dan kod heks dalam masa nyata.',
    'onboarding.understand.title': 'Fahami penglihatan warna',
    'onboarding.understand.text':
        'Pratonton simulasi untuk melihat perbezaan penglihatan warna.',
    'getStarted': 'Mula',
    'tab.assist': 'Bantuan',
    'tab.detect': 'Kesan',
    'tab.simulate': 'Simulasi',
    'tab.settings': 'Tetapan',
    'appearance': 'Paparan',
    'darkMode': 'Mod gelap',
    'darkEnabled': 'Tema gelap diaktifkan',
    'lightEnabled': 'Tema cerah diaktifkan',
    'language': 'Bahasa',
    'legal': 'Perundangan',
    'privacyPolicy': 'Dasar Privasi',
    'termsOfUse': 'Terma Penggunaan',
    'about': 'Tentang',
    'appName': 'Nama Aplikasi',
    'appVersion': 'Versi Aplikasi',
    'linkError': 'Pautan tidak dapat dibuka. Cuba lagi.',
    'original': 'Asal',
    'assistFilters': 'Penapis bantuan',
    'takePhoto': 'Ambil Foto',
    'uploadPhoto': 'Muat Naik Foto',
    'reset': 'Tetap Semula',
    'normal': 'Normal',
    'startingCamera': 'Memulakan kamera...',
    'cameraUnavailable':
        'Kamera tidak tersedia. Semak kebenaran kamera dan cuba lagi.',
    'color.Black': 'Hitam',
    'color.White': 'Putih',
    'color.Gray': 'Kelabu',
    'color.Red': 'Merah',
    'color.Orange': 'Jingga',
    'color.Yellow': 'Kuning',
    'color.Green': 'Hijau',
    'color.Teal': 'Hijau Kebiruan',
    'color.Blue': 'Biru',
    'color.Purple': 'Ungu',
    'color.Pink': 'Merah Jambu',
    'color.Brown': 'Coklat',
    'color.Charcoal': 'Arang',
    'color.Silver': 'Perak',
    'color.Maroon': 'Marun',
    'color.Coral': 'Karang',
    'color.Gold': 'Emas',
    'color.Olive': 'Zaitun',
    'color.Lime': 'Limau',
    'color.Forest Green': 'Hijau Hutan',
    'color.Mint': 'Pudina',
    'color.Cyan': 'Sian',
    'color.Sky Blue': 'Biru Langit',
    'color.Navy': 'Biru Gelap',
    'color.Indigo': 'Indigo',
    'color.Lavender': 'Lavender',
    'color.Magenta': 'Magenta',
    'color.Beige': 'Beige',
  },
  'zh_CN': {
    'tagline': '帮助色觉障碍用户更好地区分颜色。',
    'onboarding.enhance.title': '增强颜色差异',
    'onboarding.enhance.text': '当颜色难以区分时，为照片应用辅助滤镜。',
    'onboarding.identify.title': '识别周围颜色',
    'onboarding.identify.text': '使用相机实时查看颜色名称和十六进制代码。',
    'onboarding.understand.title': '了解色觉',
    'onboarding.understand.text': '预览模拟效果，了解色觉差异。',
    'getStarted': '开始使用',
    'tab.assist': '辅助',
    'tab.detect': '识别',
    'tab.simulate': '模拟',
    'tab.settings': '设置',
    'appearance': '外观',
    'darkMode': '深色模式',
    'darkEnabled': '已启用深色主题',
    'lightEnabled': '已启用浅色主题',
    'language': '语言',
    'legal': '法律信息',
    'privacyPolicy': '隐私政策',
    'termsOfUse': '使用条款',
    'about': '关于',
    'appName': '应用名称',
    'appVersion': '应用版本',
    'linkError': '无法打开链接，请重试。',
    'original': '原图',
    'assistFilters': '辅助滤镜',
    'takePhoto': '拍照',
    'uploadPhoto': '上传照片',
    'reset': '重置',
    'normal': '正常',
    'startingCamera': '正在启动相机...',
    'cameraUnavailable': '相机不可用。请检查相机权限后重试。',
    'color.Black': '黑色',
    'color.White': '白色',
    'color.Gray': '灰色',
    'color.Red': '红色',
    'color.Orange': '橙色',
    'color.Yellow': '黄色',
    'color.Green': '绿色',
    'color.Teal': '青绿色',
    'color.Blue': '蓝色',
    'color.Purple': '紫色',
    'color.Pink': '粉色',
    'color.Brown': '棕色',
    'color.Charcoal': '炭灰色',
    'color.Silver': '银色',
    'color.Maroon': '栗色',
    'color.Coral': '珊瑚色',
    'color.Gold': '金色',
    'color.Olive': '橄榄色',
    'color.Lime': '青柠色',
    'color.Forest Green': '森林绿',
    'color.Mint': '薄荷绿',
    'color.Cyan': '青色',
    'color.Sky Blue': '天蓝色',
    'color.Navy': '藏青色',
    'color.Indigo': '靛蓝色',
    'color.Lavender': '薰衣草紫',
    'color.Magenta': '洋红色',
    'color.Beige': '米色',
  },
  'ja': {
    'tagline': '色覚に特性のある方が色を区別しやすくします。',
    'onboarding.enhance.title': '色の違いを強調',
    'onboarding.enhance.text': '区別しにくい色を補助フィルターで見やすくします。',
    'onboarding.identify.title': '周囲の色を識別',
    'onboarding.identify.text': 'カメラで色名と16進コードをリアルタイムに確認します。',
    'onboarding.understand.title': '色覚を理解',
    'onboarding.understand.text': '色覚の違いをシミュレーションで確認します。',
    'getStarted': '始める',
    'tab.assist': '補助',
    'tab.detect': '検出',
    'tab.simulate': '体験',
    'tab.settings': '設定',
    'appearance': '外観',
    'darkMode': 'ダークモード',
    'darkEnabled': 'ダークテーマを使用中',
    'lightEnabled': 'ライトテーマを使用中',
    'language': '言語',
    'legal': '法的情報',
    'privacyPolicy': 'プライバシーポリシー',
    'termsOfUse': '利用規約',
    'about': 'アプリ情報',
    'appName': 'アプリ名',
    'appVersion': 'バージョン',
    'linkError': 'リンクを開けません。もう一度お試しください。',
    'original': 'オリジナル',
    'assistFilters': '補助フィルター',
    'takePhoto': '写真を撮る',
    'uploadPhoto': '写真を選ぶ',
    'reset': 'リセット',
    'normal': '通常',
    'startingCamera': 'カメラを起動中...',
    'cameraUnavailable': 'カメラを使用できません。権限を確認してください。',
    'color.Black': '黒',
    'color.White': '白',
    'color.Gray': 'グレー',
    'color.Red': '赤',
    'color.Orange': 'オレンジ',
    'color.Yellow': '黄',
    'color.Green': '緑',
    'color.Teal': '青緑',
    'color.Blue': '青',
    'color.Purple': '紫',
    'color.Pink': 'ピンク',
    'color.Brown': '茶色',
    'color.Charcoal': 'チャコール',
    'color.Silver': 'シルバー',
    'color.Maroon': 'マルーン',
    'color.Coral': 'コーラル',
    'color.Gold': 'ゴールド',
    'color.Olive': 'オリーブ',
    'color.Lime': 'ライム',
    'color.Forest Green': 'フォレストグリーン',
    'color.Mint': 'ミント',
    'color.Cyan': 'シアン',
    'color.Sky Blue': 'スカイブルー',
    'color.Navy': 'ネイビー',
    'color.Indigo': 'インディゴ',
    'color.Lavender': 'ラベンダー',
    'color.Magenta': 'マゼンタ',
    'color.Beige': 'ベージュ',
  },
  'ko': {
    'tagline': '색각 이상 사용자가 색상을 더 잘 구분하도록 돕습니다.',
    'onboarding.enhance.title': '색상 차이 강화',
    'onboarding.enhance.text': '구분하기 어려운 색상에 보조 필터를 적용합니다.',
    'onboarding.identify.title': '주변 색상 식별',
    'onboarding.identify.text': '카메라로 색상 이름과 HEX 코드를 실시간 확인합니다.',
    'onboarding.understand.title': '색각 이해',
    'onboarding.understand.text': '시뮬레이션으로 색각 차이를 미리 봅니다.',
    'getStarted': '시작하기',
    'tab.assist': '보조',
    'tab.detect': '감지',
    'tab.simulate': '시뮬레이션',
    'tab.settings': '설정',
    'appearance': '화면 설정',
    'darkMode': '다크 모드',
    'darkEnabled': '다크 테마 사용 중',
    'lightEnabled': '라이트 테마 사용 중',
    'language': '언어',
    'legal': '법적 고지',
    'privacyPolicy': '개인정보 처리방침',
    'termsOfUse': '이용 약관',
    'about': '정보',
    'appName': '앱 이름',
    'appVersion': '앱 버전',
    'linkError': '링크를 열 수 없습니다. 다시 시도하세요.',
    'original': '원본',
    'assistFilters': '보조 필터',
    'takePhoto': '사진 촬영',
    'uploadPhoto': '사진 업로드',
    'reset': '초기화',
    'normal': '일반',
    'startingCamera': '카메라 시작 중...',
    'cameraUnavailable': '카메라를 사용할 수 없습니다. 권한을 확인하세요.',
    'color.Black': '검정',
    'color.White': '흰색',
    'color.Gray': '회색',
    'color.Red': '빨강',
    'color.Orange': '주황',
    'color.Yellow': '노랑',
    'color.Green': '초록',
    'color.Teal': '청록',
    'color.Blue': '파랑',
    'color.Purple': '보라',
    'color.Pink': '분홍',
    'color.Brown': '갈색',
    'color.Charcoal': '차콜',
    'color.Silver': '은색',
    'color.Maroon': '적갈색',
    'color.Coral': '코랄',
    'color.Gold': '금색',
    'color.Olive': '올리브',
    'color.Lime': '라임',
    'color.Forest Green': '진녹색',
    'color.Mint': '민트',
    'color.Cyan': '시안',
    'color.Sky Blue': '하늘색',
    'color.Navy': '남색',
    'color.Indigo': '인디고',
    'color.Lavender': '라벤더',
    'color.Magenta': '마젠타',
    'color.Beige': '베이지',
  },
  'es': {
    'tagline':
        'Ayuda a las personas daltónicas a distinguir mejor los colores.',
    'onboarding.enhance.title': 'Mejora las diferencias de color',
    'onboarding.enhance.text':
        'Aplica filtros de ayuda cuando sea difícil distinguir colores.',
    'onboarding.identify.title': 'Identifica los colores cercanos',
    'onboarding.identify.text':
        'Usa la cámara para ver el nombre y código hexadecimal en tiempo real.',
    'onboarding.understand.title': 'Comprende la visión del color',
    'onboarding.understand.text':
        'Previsualiza simulaciones de diferentes percepciones del color.',
    'getStarted': 'Comenzar',
    'tab.assist': 'Ayuda',
    'tab.detect': 'Detectar',
    'tab.simulate': 'Simular',
    'tab.settings': 'Ajustes',
    'appearance': 'Apariencia',
    'darkMode': 'Modo oscuro',
    'darkEnabled': 'Tema oscuro activado',
    'lightEnabled': 'Tema claro activado',
    'language': 'Idioma',
    'legal': 'Legal',
    'privacyPolicy': 'Política de privacidad',
    'termsOfUse': 'Términos de uso',
    'about': 'Información',
    'appName': 'Nombre de la app',
    'appVersion': 'Versión de la app',
    'linkError': 'No se puede abrir el enlace. Inténtalo de nuevo.',
    'original': 'Original',
    'assistFilters': 'Filtros de ayuda',
    'takePhoto': 'Tomar foto',
    'uploadPhoto': 'Subir foto',
    'reset': 'Restablecer',
    'normal': 'Normal',
    'startingCamera': 'Iniciando cámara...',
    'cameraUnavailable':
        'Cámara no disponible. Revisa el permiso e inténtalo de nuevo.',
    'color.Black': 'Negro',
    'color.White': 'Blanco',
    'color.Gray': 'Gris',
    'color.Red': 'Rojo',
    'color.Orange': 'Naranja',
    'color.Yellow': 'Amarillo',
    'color.Green': 'Verde',
    'color.Teal': 'Verde azulado',
    'color.Blue': 'Azul',
    'color.Purple': 'Morado',
    'color.Pink': 'Rosa',
    'color.Brown': 'Marrón',
    'color.Charcoal': 'Carbón',
    'color.Silver': 'Plateado',
    'color.Maroon': 'Granate',
    'color.Coral': 'Coral',
    'color.Gold': 'Dorado',
    'color.Olive': 'Oliva',
    'color.Lime': 'Lima',
    'color.Forest Green': 'Verde bosque',
    'color.Mint': 'Menta',
    'color.Cyan': 'Cian',
    'color.Sky Blue': 'Azul cielo',
    'color.Navy': 'Azul marino',
    'color.Indigo': 'Índigo',
    'color.Lavender': 'Lavanda',
    'color.Magenta': 'Magenta',
    'color.Beige': 'Beige',
  },
  'fr': {
    'tagline':
        'Aide les personnes daltoniennes à mieux distinguer les couleurs.',
    'onboarding.enhance.title': 'Renforcer les différences',
    'onboarding.enhance.text':
        'Appliquez des filtres lorsque les couleurs sont difficiles à distinguer.',
    'onboarding.identify.title': 'Identifier les couleurs',
    'onboarding.identify.text':
        'Utilisez la caméra pour voir le nom et le code hexadécimal en temps réel.',
    'onboarding.understand.title': 'Comprendre la vision des couleurs',
    'onboarding.understand.text':
        'Prévisualisez des simulations des différences de vision des couleurs.',
    'getStarted': 'Commencer',
    'tab.assist': 'Aide',
    'tab.detect': 'Détecter',
    'tab.simulate': 'Simuler',
    'tab.settings': 'Réglages',
    'appearance': 'Apparence',
    'darkMode': 'Mode sombre',
    'darkEnabled': 'Thème sombre activé',
    'lightEnabled': 'Thème clair activé',
    'language': 'Langue',
    'legal': 'Mentions légales',
    'privacyPolicy': 'Politique de confidentialité',
    'termsOfUse': "Conditions d'utilisation",
    'about': 'À propos',
    'appName': "Nom de l'app",
    'appVersion': "Version de l'app",
    'linkError': "Impossible d'ouvrir le lien. Réessayez.",
    'original': 'Original',
    'assistFilters': "Filtres d'aide",
    'takePhoto': 'Prendre une photo',
    'uploadPhoto': 'Importer une photo',
    'reset': 'Réinitialiser',
    'normal': 'Normal',
    'startingCamera': 'Démarrage de la caméra...',
    'cameraUnavailable': 'Caméra indisponible. Vérifiez les autorisations.',
    'color.Black': 'Noir',
    'color.White': 'Blanc',
    'color.Gray': 'Gris',
    'color.Red': 'Rouge',
    'color.Orange': 'Orange',
    'color.Yellow': 'Jaune',
    'color.Green': 'Vert',
    'color.Teal': 'Turquoise',
    'color.Blue': 'Bleu',
    'color.Purple': 'Violet',
    'color.Pink': 'Rose',
    'color.Brown': 'Marron',
    'color.Charcoal': 'Anthracite',
    'color.Silver': 'Argent',
    'color.Maroon': 'Bordeaux',
    'color.Coral': 'Corail',
    'color.Gold': 'Doré',
    'color.Olive': 'Olive',
    'color.Lime': 'Citron vert',
    'color.Forest Green': 'Vert forêt',
    'color.Mint': 'Menthe',
    'color.Cyan': 'Cyan',
    'color.Sky Blue': 'Bleu ciel',
    'color.Navy': 'Bleu marine',
    'color.Indigo': 'Indigo',
    'color.Lavender': 'Lavande',
    'color.Magenta': 'Magenta',
    'color.Beige': 'Beige',
  },
  'it': {
    'tagline': 'Aiuta le persone daltoniche a distinguere meglio i colori.',
    'onboarding.enhance.title': 'Migliora le differenze di colore',
    'onboarding.enhance.text':
        'Applica filtri di assistenza quando i colori sono difficili da distinguere.',
    'onboarding.identify.title': 'Identifica i colori intorno a te',
    'onboarding.identify.text':
        'Usa la fotocamera per vedere nome e codice esadecimale in tempo reale.',
    'onboarding.understand.title': 'Comprendi la visione dei colori',
    'onboarding.understand.text':
        'Visualizza simulazioni delle differenze nella percezione dei colori.',
    'getStarted': 'Inizia',
    'tab.assist': 'Assistenza',
    'tab.detect': 'Rileva',
    'tab.simulate': 'Simula',
    'tab.settings': 'Impostazioni',
    'appearance': 'Aspetto',
    'darkMode': 'Modalità scura',
    'darkEnabled': 'Tema scuro attivo',
    'lightEnabled': 'Tema chiaro attivo',
    'language': 'Lingua',
    'legal': 'Note legali',
    'privacyPolicy': 'Informativa sulla privacy',
    'termsOfUse': "Termini d'uso",
    'about': 'Informazioni',
    'appName': "Nome dell'app",
    'appVersion': "Versione dell'app",
    'linkError': 'Impossibile aprire il link. Riprova.',
    'original': 'Originale',
    'assistFilters': 'Filtri di assistenza',
    'takePhoto': 'Scatta foto',
    'uploadPhoto': 'Carica foto',
    'reset': 'Ripristina',
    'normal': 'Normale',
    'startingCamera': 'Avvio fotocamera...',
    'cameraUnavailable': 'Fotocamera non disponibile. Controlla i permessi.',
    'color.Black': 'Nero',
    'color.White': 'Bianco',
    'color.Gray': 'Grigio',
    'color.Red': 'Rosso',
    'color.Orange': 'Arancione',
    'color.Yellow': 'Giallo',
    'color.Green': 'Verde',
    'color.Teal': 'Verde acqua',
    'color.Blue': 'Blu',
    'color.Purple': 'Viola',
    'color.Pink': 'Rosa',
    'color.Brown': 'Marrone',
    'color.Charcoal': 'Antracite',
    'color.Silver': 'Argento',
    'color.Maroon': 'Bordeaux',
    'color.Coral': 'Corallo',
    'color.Gold': 'Oro',
    'color.Olive': 'Oliva',
    'color.Lime': 'Lime',
    'color.Forest Green': 'Verde foresta',
    'color.Mint': 'Menta',
    'color.Cyan': 'Ciano',
    'color.Sky Blue': 'Azzurro cielo',
    'color.Navy': 'Blu navy',
    'color.Indigo': 'Indaco',
    'color.Lavender': 'Lavanda',
    'color.Magenta': 'Magenta',
    'color.Beige': 'Beige',
  },
  'de': {
    'tagline':
        'Hilft Menschen mit Farbsehschwäche, Farben besser zu unterscheiden.',
    'onboarding.enhance.title': 'Farbunterschiede verstärken',
    'onboarding.enhance.text':
        'Wenden Sie Hilfsfilter an, wenn Farben schwer zu unterscheiden sind.',
    'onboarding.identify.title': 'Farben in der Umgebung erkennen',
    'onboarding.identify.text':
        'Prüfen Sie Farbname und Hex-Code live mit der Kamera.',
    'onboarding.understand.title': 'Farbsehen verstehen',
    'onboarding.understand.text':
        'Sehen Sie Simulationen verschiedener Farbwahrnehmungen an.',
    'getStarted': 'Loslegen',
    'tab.assist': 'Hilfe',
    'tab.detect': 'Erkennen',
    'tab.simulate': 'Simulieren',
    'tab.settings': 'Einstellungen',
    'appearance': 'Darstellung',
    'darkMode': 'Dunkelmodus',
    'darkEnabled': 'Dunkles Design aktiviert',
    'lightEnabled': 'Helles Design aktiviert',
    'language': 'Sprache',
    'legal': 'Rechtliches',
    'privacyPolicy': 'Datenschutzrichtlinie',
    'termsOfUse': 'Nutzungsbedingungen',
    'about': 'Info',
    'appName': 'App-Name',
    'appVersion': 'App-Version',
    'linkError': 'Link kann nicht geöffnet werden. Bitte erneut versuchen.',
    'original': 'Original',
    'assistFilters': 'Hilfsfilter',
    'takePhoto': 'Foto aufnehmen',
    'uploadPhoto': 'Foto hochladen',
    'reset': 'Zurücksetzen',
    'normal': 'Normal',
    'startingCamera': 'Kamera wird gestartet...',
    'cameraUnavailable': 'Kamera nicht verfügbar. Prüfen Sie die Berechtigung.',
    'color.Black': 'Schwarz',
    'color.White': 'Weiß',
    'color.Gray': 'Grau',
    'color.Red': 'Rot',
    'color.Orange': 'Orange',
    'color.Yellow': 'Gelb',
    'color.Green': 'Grün',
    'color.Teal': 'Blaugrün',
    'color.Blue': 'Blau',
    'color.Purple': 'Lila',
    'color.Pink': 'Rosa',
    'color.Brown': 'Braun',
    'color.Charcoal': 'Anthrazit',
    'color.Silver': 'Silber',
    'color.Maroon': 'Kastanienrot',
    'color.Coral': 'Koralle',
    'color.Gold': 'Gold',
    'color.Olive': 'Oliv',
    'color.Lime': 'Limette',
    'color.Forest Green': 'Waldgrün',
    'color.Mint': 'Mint',
    'color.Cyan': 'Cyan',
    'color.Sky Blue': 'Himmelblau',
    'color.Navy': 'Marineblau',
    'color.Indigo': 'Indigo',
    'color.Lavender': 'Lavendel',
    'color.Magenta': 'Magenta',
    'color.Beige': 'Beige',
  },

  'zh_TW': {
    'tagline': '幫助色覺障礙使用者更容易分辨顏色。',
    'onboarding.enhance.title': '增強顏色差異',
    'onboarding.enhance.text': '當顏色難以分辨時，為照片套用輔助濾鏡。',
    'onboarding.identify.title': '辨識周圍顏色',
    'onboarding.identify.text': '使用相機即時查看顏色名稱和十六進位代碼。',
    'onboarding.understand.title': '了解色覺',
    'onboarding.understand.text': '預覽模擬效果，了解色覺差異。',
    'getStarted': '開始使用',
    'tab.assist': '輔助',
    'tab.detect': '辨識',
    'tab.simulate': '模擬',
    'tab.settings': '設定',
    'appearance': '外觀',
    'darkMode': '深色模式',
    'darkEnabled': '已啟用深色主題',
    'lightEnabled': '已啟用淺色主題',
    'language': '語言',
    'legal': '法律資訊',
    'privacyPolicy': '隱私權政策',
    'termsOfUse': '使用條款',
    'about': '關於',
    'appName': '應用程式名稱',
    'appVersion': '應用程式版本',
    'linkError': '無法開啟連結，請再試一次。',
    'original': '原圖',
    'assistFilters': '輔助濾鏡',
    'takePhoto': '拍照',
    'uploadPhoto': '上傳照片',
    'reset': '重設',
    'normal': '正常',
    'startingCamera': '正在啟動相機...',
    'cameraUnavailable': '相機無法使用。請檢查相機權限後再試一次。',
    'color.Black': '黑色',
    'color.White': '白色',
    'color.Gray': '灰色',
    'color.Red': '紅色',
    'color.Orange': '橙色',
    'color.Yellow': '黃色',
    'color.Green': '綠色',
    'color.Teal': '藍綠色',
    'color.Blue': '藍色',
    'color.Purple': '紫色',
    'color.Pink': '粉紅色',
    'color.Brown': '棕色',
    'color.Charcoal': '炭灰色',
    'color.Silver': '銀色',
    'color.Maroon': '栗色',
    'color.Coral': '珊瑚色',
    'color.Gold': '金色',
    'color.Olive': '橄欖色',
    'color.Lime': '萊姆色',
    'color.Forest Green': '森林綠',
    'color.Mint': '薄荷綠',
    'color.Cyan': '青色',
    'color.Sky Blue': '天藍色',
    'color.Navy': '海軍藍',
    'color.Indigo': '靛藍色',
    'color.Lavender': '薰衣草紫',
    'color.Magenta': '洋紅色',
    'color.Beige': '米色',
  },
  'th': {
    'tagline': 'ช่วยให้ผู้มีภาวะตาบอดสีแยกแยะสีได้ดีขึ้น',
    'onboarding.enhance.title': 'เพิ่มความแตกต่างของสี',
    'onboarding.enhance.text': 'ใช้ฟิลเตอร์ช่วยกับรูปภาพเมื่อแยกสีได้ยาก',
    'onboarding.identify.title': 'ระบุสีรอบตัวคุณ',
    'onboarding.identify.text': 'ใช้กล้องดูชื่อสีและรหัส HEX แบบเรียลไทม์',
    'onboarding.understand.title': 'เข้าใจการมองเห็นสี',
    'onboarding.understand.text':
        'ดูตัวอย่างการจำลองความแตกต่างของการมองเห็นสี',
    'getStarted': 'เริ่มใช้งาน',
    'tab.assist': 'ช่วยเหลือ',
    'tab.detect': 'ตรวจจับ',
    'tab.simulate': 'จำลอง',
    'tab.settings': 'ตั้งค่า',
    'appearance': 'การแสดงผล',
    'darkMode': 'โหมดมืด',
    'darkEnabled': 'เปิดใช้ธีมมืด',
    'lightEnabled': 'เปิดใช้ธีมสว่าง',
    'language': 'ภาษา',
    'legal': 'ข้อมูลทางกฎหมาย',
    'privacyPolicy': 'นโยบายความเป็นส่วนตัว',
    'termsOfUse': 'ข้อกำหนดการใช้งาน',
    'about': 'เกี่ยวกับ',
    'appName': 'ชื่อแอป',
    'appVersion': 'เวอร์ชันแอป',
    'linkError': 'ไม่สามารถเปิดลิงก์ได้ โปรดลองอีกครั้ง',
    'original': 'ต้นฉบับ',
    'assistFilters': 'ฟิลเตอร์ช่วยเหลือ',
    'takePhoto': 'ถ่ายรูป',
    'uploadPhoto': 'อัปโหลดรูป',
    'reset': 'รีเซ็ต',
    'normal': 'ปกติ',
    'startingCamera': 'กำลังเปิดกล้อง...',
    'cameraUnavailable': 'ไม่สามารถใช้กล้องได้ โปรดตรวจสอบสิทธิ์กล้อง',
    'color.Black': 'ดำ',
    'color.White': 'ขาว',
    'color.Gray': 'เทา',
    'color.Red': 'แดง',
    'color.Orange': 'ส้ม',
    'color.Yellow': 'เหลือง',
    'color.Green': 'เขียว',
    'color.Teal': 'เขียวอมฟ้า',
    'color.Blue': 'น้ำเงิน',
    'color.Purple': 'ม่วง',
    'color.Pink': 'ชมพู',
    'color.Brown': 'น้ำตาล',
    'color.Charcoal': 'เทาเข้ม',
    'color.Silver': 'เงิน',
    'color.Maroon': 'แดงเลือดหมู',
    'color.Coral': 'ปะการัง',
    'color.Gold': 'ทอง',
    'color.Olive': 'เขียวมะกอก',
    'color.Lime': 'เขียวมะนาว',
    'color.Forest Green': 'เขียวป่า',
    'color.Mint': 'มิ้นต์',
    'color.Cyan': 'ฟ้าอมเขียว',
    'color.Sky Blue': 'ฟ้า',
    'color.Navy': 'กรมท่า',
    'color.Indigo': 'คราม',
    'color.Lavender': 'ลาเวนเดอร์',
    'color.Magenta': 'บานเย็น',
    'color.Beige': 'เบจ',
  },
  'hi': {
    'tagline':
        'रंग दृष्टि की कमी वाले उपयोगकर्ताओं को रंग बेहतर पहचानने में मदद करता है।',
    'onboarding.enhance.title': 'रंगों का अंतर बढ़ाएँ',
    'onboarding.enhance.text':
        'जब रंग अलग करना कठिन हो तब फोटो पर सहायक फ़िल्टर लगाएँ।',
    'onboarding.identify.title': 'आस-पास के रंग पहचानें',
    'onboarding.identify.text': 'कैमरे से रंग का नाम और HEX कोड तुरंत देखें।',
    'onboarding.understand.title': 'रंग दृष्टि को समझें',
    'onboarding.understand.text': 'रंग दृष्टि के अंतर का सिमुलेशन देखें।',
    'getStarted': 'शुरू करें',
    'tab.assist': 'सहायता',
    'tab.detect': 'पहचानें',
    'tab.simulate': 'सिमुलेट',
    'tab.settings': 'सेटिंग्स',
    'appearance': 'दिखावट',
    'darkMode': 'डार्क मोड',
    'darkEnabled': 'डार्क थीम चालू है',
    'lightEnabled': 'लाइट थीम चालू है',
    'language': 'भाषा',
    'legal': 'कानूनी',
    'privacyPolicy': 'गोपनीयता नीति',
    'termsOfUse': 'उपयोग की शर्तें',
    'about': 'जानकारी',
    'appName': 'ऐप का नाम',
    'appVersion': 'ऐप संस्करण',
    'linkError': 'लिंक नहीं खुल सका। फिर से प्रयास करें।',
    'original': 'मूल',
    'assistFilters': 'सहायक फ़िल्टर',
    'takePhoto': 'फोटो लें',
    'uploadPhoto': 'फोटो अपलोड करें',
    'reset': 'रीसेट',
    'normal': 'सामान्य',
    'startingCamera': 'कैमरा शुरू हो रहा है...',
    'cameraUnavailable': 'कैमरा उपलब्ध नहीं है। कैमरा अनुमति जाँचें।',
    'color.Black': 'काला',
    'color.White': 'सफेद',
    'color.Gray': 'धूसर',
    'color.Red': 'लाल',
    'color.Orange': 'नारंगी',
    'color.Yellow': 'पीला',
    'color.Green': 'हरा',
    'color.Teal': 'हरा-नीला',
    'color.Blue': 'नीला',
    'color.Purple': 'बैंगनी',
    'color.Pink': 'गुलाबी',
    'color.Brown': 'भूरा',
    'color.Charcoal': 'कोयला धूसर',
    'color.Silver': 'चाँदी',
    'color.Maroon': 'मैरून',
    'color.Coral': 'मूंगा',
    'color.Gold': 'सुनहरा',
    'color.Olive': 'जैतूनी',
    'color.Lime': 'लाइम',
    'color.Forest Green': 'गहरा हरा',
    'color.Mint': 'मिंट',
    'color.Cyan': 'सायन',
    'color.Sky Blue': 'आसमानी नीला',
    'color.Navy': 'गहरा नीला',
    'color.Indigo': 'नील',
    'color.Lavender': 'लैवेंडर',
    'color.Magenta': 'मैजेंटा',
    'color.Beige': 'बेज',
  },
  'ar': {
    'tagline':
        'يساعد المستخدمين الذين يعانون من ضعف رؤية الألوان على تمييزها بشكل أفضل.',
    'onboarding.enhance.title': 'تعزيز اختلافات الألوان',
    'onboarding.enhance.text':
        'طبّق فلاتر مساعدة على الصور عندما يصعب تمييز الألوان.',
    'onboarding.identify.title': 'تعرّف على الألوان من حولك',
    'onboarding.identify.text':
        'استخدم الكاميرا لمعرفة اسم اللون ورمز HEX فورًا.',
    'onboarding.understand.title': 'فهم رؤية الألوان',
    'onboarding.understand.text': 'عاين محاكاة توضّح اختلافات رؤية الألوان.',
    'getStarted': 'ابدأ',
    'tab.assist': 'مساعدة',
    'tab.detect': 'كشف',
    'tab.simulate': 'محاكاة',
    'tab.settings': 'الإعدادات',
    'appearance': 'المظهر',
    'darkMode': 'الوضع الداكن',
    'darkEnabled': 'تم تفعيل المظهر الداكن',
    'lightEnabled': 'تم تفعيل المظهر الفاتح',
    'language': 'اللغة',
    'legal': 'قانوني',
    'privacyPolicy': 'سياسة الخصوصية',
    'termsOfUse': 'شروط الاستخدام',
    'about': 'حول',
    'appName': 'اسم التطبيق',
    'appVersion': 'إصدار التطبيق',
    'linkError': 'تعذر فتح الرابط. حاول مرة أخرى.',
    'original': 'الأصل',
    'assistFilters': 'فلاتر المساعدة',
    'takePhoto': 'التقاط صورة',
    'uploadPhoto': 'رفع صورة',
    'reset': 'إعادة تعيين',
    'normal': 'عادي',
    'startingCamera': 'جارٍ تشغيل الكاميرا...',
    'cameraUnavailable': 'الكاميرا غير متاحة. تحقق من إذن الكاميرا.',
    'color.Black': 'أسود',
    'color.White': 'أبيض',
    'color.Gray': 'رمادي',
    'color.Red': 'أحمر',
    'color.Orange': 'برتقالي',
    'color.Yellow': 'أصفر',
    'color.Green': 'أخضر',
    'color.Teal': 'أزرق مخضر',
    'color.Blue': 'أزرق',
    'color.Purple': 'بنفسجي',
    'color.Pink': 'وردي',
    'color.Brown': 'بني',
    'color.Charcoal': 'فحمي',
    'color.Silver': 'فضي',
    'color.Maroon': 'خمري',
    'color.Coral': 'مرجاني',
    'color.Gold': 'ذهبي',
    'color.Olive': 'زيتوني',
    'color.Lime': 'ليموني',
    'color.Forest Green': 'أخضر غامق',
    'color.Mint': 'نعناعي',
    'color.Cyan': 'سماوي',
    'color.Sky Blue': 'أزرق سماوي',
    'color.Navy': 'كحلي',
    'color.Indigo': 'نيلي',
    'color.Lavender': 'خزامي',
    'color.Magenta': 'أرجواني',
    'color.Beige': 'بيج',
  },
};
