import 'package:flutter/widgets.dart';

enum AppLanguage {
  english('en', 'English'),
  malay('ms', 'Bahasa Melayu'),
  chinese('zh', '中文'),
  japanese('ja', '日本語'),
  korean('ko', '한국어'),
  spanish('es', 'Español'),
  french('fr', 'Français'),
  italian('it', 'Italiano'),
  german('de', 'Deutsch');

  const AppLanguage(this.code, this.label);
  final String code;
  final String label;

  Locale get locale => Locale(code);

  static AppLanguage fromCode(String? code) {
    return values.firstWhere(
      (language) => language.code == code,
      orElse: () => AppLanguage.english,
    );
  }
}

class AppStrings {
  const AppStrings(this.language);
  final AppLanguage language;

  String t(String key) =>
      _translations[language.code]?[key] ?? _translations['en']![key] ?? key;

  String colorName(String englishName) => t('color.$englishName');
}

const _translations = <String, Map<String, String>>{
  'en': {
    'tagline': 'Helping colorblind users distinguish colors better.',
    'onboarding.enhance.title': 'Enhance color differences',
    'onboarding.enhance.text':
        'Apply assistive filters to photos when colors are difficult to tell apart.',
    'onboarding.identify.title': 'Identify colors around you',
    'onboarding.identify.text':
        'Use the camera to check a color name and its hex code in real time.',
    'onboarding.understand.title': 'Understand color vision',
    'onboarding.understand.text':
        'Preview simulations that show how color vision differences can appear.',
    'getStarted': 'Get Started',
    'tab.assist': 'Assist',
    'tab.detect': 'Detect',
    'tab.simulate': 'Simulate',
    'tab.settings': 'Settings',
    'appearance': 'Appearance',
    'darkMode': 'Dark mode',
    'darkEnabled': 'Dark theme enabled',
    'lightEnabled': 'Light theme enabled',
    'language': 'Language',
    'legal': 'Legal',
    'privacyPolicy': 'Privacy Policy',
    'termsOfUse': 'Terms of Use',
    'about': 'About',
    'appName': 'App Name',
    'appVersion': 'App Version',
    'linkError': 'Unable to open the link. Please try again.',
    'original': 'Original',
    'assistFilters': 'Assist filters',
    'takePhoto': 'Take Photo',
    'uploadPhoto': 'Upload Photo',
    'reset': 'Reset',
    'normal': 'Normal',
    'startingCamera': 'Starting camera...',
    'cameraUnavailable':
        'Camera unavailable. Check camera permission and try again.',
    'color.Black': 'Black',
    'color.White': 'White',
    'color.Gray': 'Gray',
    'color.Red': 'Red',
    'color.Orange': 'Orange',
    'color.Yellow': 'Yellow',
    'color.Green': 'Green',
    'color.Teal': 'Teal',
    'color.Blue': 'Blue',
    'color.Purple': 'Purple',
    'color.Pink': 'Pink',
    'color.Brown': 'Brown',
  },
  'ms': {
    'tagline':
        'Membantu pengguna buta warna membezakan warna dengan lebih baik.',
    'onboarding.enhance.title': 'Jelaskan perbezaan warna',
    'onboarding.enhance.text':
        'Gunakan penapis bantuan pada foto apabila warna sukar dibezakan.',
    'onboarding.identify.title': 'Kenal pasti warna di sekeliling',
    'onboarding.identify.text':
        'Gunakan kamera untuk menyemak nama warna dan kod heks dalam masa nyata.',
    'onboarding.understand.title': 'Fahami penglihatan warna',
    'onboarding.understand.text':
        'Pratonton simulasi untuk melihat perbezaan penglihatan warna.',
    'getStarted': 'Mula',
    'tab.assist': 'Bantuan',
    'tab.detect': 'Kesan',
    'tab.simulate': 'Simulasi',
    'tab.settings': 'Tetapan',
    'appearance': 'Paparan',
    'darkMode': 'Mod gelap',
    'darkEnabled': 'Tema gelap diaktifkan',
    'lightEnabled': 'Tema cerah diaktifkan',
    'language': 'Bahasa',
    'legal': 'Perundangan',
    'privacyPolicy': 'Dasar Privasi',
    'termsOfUse': 'Terma Penggunaan',
    'about': 'Tentang',
    'appName': 'Nama Aplikasi',
    'appVersion': 'Versi Aplikasi',
    'linkError': 'Pautan tidak dapat dibuka. Cuba lagi.',
    'original': 'Asal',
    'assistFilters': 'Penapis bantuan',
    'takePhoto': 'Ambil Foto',
    'uploadPhoto': 'Muat Naik Foto',
    'reset': 'Tetap Semula',
    'normal': 'Normal',
    'startingCamera': 'Memulakan kamera...',
    'cameraUnavailable':
        'Kamera tidak tersedia. Semak kebenaran kamera dan cuba lagi.',
    'color.Black': 'Hitam',
    'color.White': 'Putih',
    'color.Gray': 'Kelabu',
    'color.Red': 'Merah',
    'color.Orange': 'Jingga',
    'color.Yellow': 'Kuning',
    'color.Green': 'Hijau',
    'color.Teal': 'Hijau Kebiruan',
    'color.Blue': 'Biru',
    'color.Purple': 'Ungu',
    'color.Pink': 'Merah Jambu',
    'color.Brown': 'Coklat',
  },
  'zh': {
    'tagline': '帮助色觉障碍用户更好地区分颜色。',
    'onboarding.enhance.title': '增强颜色差异',
    'onboarding.enhance.text': '当颜色难以区分时，为照片应用辅助滤镜。',
    'onboarding.identify.title': '识别周围颜色',
    'onboarding.identify.text': '使用相机实时查看颜色名称和十六进制代码。',
    'onboarding.understand.title': '了解色觉',
    'onboarding.understand.text': '预览模拟效果，了解色觉差异。',
    'getStarted': '开始使用',
    'tab.assist': '辅助',
    'tab.detect': '识别',
    'tab.simulate': '模拟',
    'tab.settings': '设置',
    'appearance': '外观',
    'darkMode': '深色模式',
    'darkEnabled': '已启用深色主题',
    'lightEnabled': '已启用浅色主题',
    'language': '语言',
    'legal': '法律信息',
    'privacyPolicy': '隐私政策',
    'termsOfUse': '使用条款',
    'about': '关于',
    'appName': '应用名称',
    'appVersion': '应用版本',
    'linkError': '无法打开链接，请重试。',
    'original': '原图',
    'assistFilters': '辅助滤镜',
    'takePhoto': '拍照',
    'uploadPhoto': '上传照片',
    'reset': '重置',
    'normal': '正常',
    'startingCamera': '正在启动相机...',
    'cameraUnavailable': '相机不可用。请检查相机权限后重试。',
    'color.Black': '黑色',
    'color.White': '白色',
    'color.Gray': '灰色',
    'color.Red': '红色',
    'color.Orange': '橙色',
    'color.Yellow': '黄色',
    'color.Green': '绿色',
    'color.Teal': '青绿色',
    'color.Blue': '蓝色',
    'color.Purple': '紫色',
    'color.Pink': '粉色',
    'color.Brown': '棕色',
  },
  'ja': {
    'tagline': '色覚に特性のある方が色を区別しやすくします。',
    'onboarding.enhance.title': '色の違いを強調',
    'onboarding.enhance.text': '区別しにくい色を補助フィルターで見やすくします。',
    'onboarding.identify.title': '周囲の色を識別',
    'onboarding.identify.text': 'カメラで色名と16進コードをリアルタイムに確認します。',
    'onboarding.understand.title': '色覚を理解',
    'onboarding.understand.text': '色覚の違いをシミュレーションで確認します。',
    'getStarted': '始める',
    'tab.assist': '補助',
    'tab.detect': '検出',
    'tab.simulate': '体験',
    'tab.settings': '設定',
    'appearance': '外観',
    'darkMode': 'ダークモード',
    'darkEnabled': 'ダークテーマを使用中',
    'lightEnabled': 'ライトテーマを使用中',
    'language': '言語',
    'legal': '法的情報',
    'privacyPolicy': 'プライバシーポリシー',
    'termsOfUse': '利用規約',
    'about': 'アプリ情報',
    'appName': 'アプリ名',
    'appVersion': 'バージョン',
    'linkError': 'リンクを開けません。もう一度お試しください。',
    'original': 'オリジナル',
    'assistFilters': '補助フィルター',
    'takePhoto': '写真を撮る',
    'uploadPhoto': '写真を選ぶ',
    'reset': 'リセット',
    'normal': '通常',
    'startingCamera': 'カメラを起動中...',
    'cameraUnavailable': 'カメラを使用できません。権限を確認してください。',
    'color.Black': '黒',
    'color.White': '白',
    'color.Gray': 'グレー',
    'color.Red': '赤',
    'color.Orange': 'オレンジ',
    'color.Yellow': '黄',
    'color.Green': '緑',
    'color.Teal': '青緑',
    'color.Blue': '青',
    'color.Purple': '紫',
    'color.Pink': 'ピンク',
    'color.Brown': '茶色',
  },
  'ko': {
    'tagline': '색각 이상 사용자가 색상을 더 잘 구분하도록 돕습니다.',
    'onboarding.enhance.title': '색상 차이 강화',
    'onboarding.enhance.text': '구분하기 어려운 색상에 보조 필터를 적용합니다.',
    'onboarding.identify.title': '주변 색상 식별',
    'onboarding.identify.text': '카메라로 색상 이름과 HEX 코드를 실시간 확인합니다.',
    'onboarding.understand.title': '색각 이해',
    'onboarding.understand.text': '시뮬레이션으로 색각 차이를 미리 봅니다.',
    'getStarted': '시작하기',
    'tab.assist': '보조',
    'tab.detect': '감지',
    'tab.simulate': '시뮬레이션',
    'tab.settings': '설정',
    'appearance': '화면 설정',
    'darkMode': '다크 모드',
    'darkEnabled': '다크 테마 사용 중',
    'lightEnabled': '라이트 테마 사용 중',
    'language': '언어',
    'legal': '법적 고지',
    'privacyPolicy': '개인정보 처리방침',
    'termsOfUse': '이용 약관',
    'about': '정보',
    'appName': '앱 이름',
    'appVersion': '앱 버전',
    'linkError': '링크를 열 수 없습니다. 다시 시도하세요.',
    'original': '원본',
    'assistFilters': '보조 필터',
    'takePhoto': '사진 촬영',
    'uploadPhoto': '사진 업로드',
    'reset': '초기화',
    'normal': '일반',
    'startingCamera': '카메라 시작 중...',
    'cameraUnavailable': '카메라를 사용할 수 없습니다. 권한을 확인하세요.',
    'color.Black': '검정',
    'color.White': '흰색',
    'color.Gray': '회색',
    'color.Red': '빨강',
    'color.Orange': '주황',
    'color.Yellow': '노랑',
    'color.Green': '초록',
    'color.Teal': '청록',
    'color.Blue': '파랑',
    'color.Purple': '보라',
    'color.Pink': '분홍',
    'color.Brown': '갈색',
  },
  'es': {
    'tagline':
        'Ayuda a las personas daltónicas a distinguir mejor los colores.',
    'onboarding.enhance.title': 'Mejora las diferencias de color',
    'onboarding.enhance.text':
        'Aplica filtros de ayuda cuando sea difícil distinguir colores.',
    'onboarding.identify.title': 'Identifica los colores cercanos',
    'onboarding.identify.text':
        'Usa la cámara para ver el nombre y código hexadecimal en tiempo real.',
    'onboarding.understand.title': 'Comprende la visión del color',
    'onboarding.understand.text':
        'Previsualiza simulaciones de diferentes percepciones del color.',
    'getStarted': 'Comenzar',
    'tab.assist': 'Ayuda',
    'tab.detect': 'Detectar',
    'tab.simulate': 'Simular',
    'tab.settings': 'Ajustes',
    'appearance': 'Apariencia',
    'darkMode': 'Modo oscuro',
    'darkEnabled': 'Tema oscuro activado',
    'lightEnabled': 'Tema claro activado',
    'language': 'Idioma',
    'legal': 'Legal',
    'privacyPolicy': 'Política de privacidad',
    'termsOfUse': 'Términos de uso',
    'about': 'Información',
    'appName': 'Nombre de la app',
    'appVersion': 'Versión de la app',
    'linkError': 'No se puede abrir el enlace. Inténtalo de nuevo.',
    'original': 'Original',
    'assistFilters': 'Filtros de ayuda',
    'takePhoto': 'Tomar foto',
    'uploadPhoto': 'Subir foto',
    'reset': 'Restablecer',
    'normal': 'Normal',
    'startingCamera': 'Iniciando cámara...',
    'cameraUnavailable':
        'Cámara no disponible. Revisa el permiso e inténtalo de nuevo.',
    'color.Black': 'Negro',
    'color.White': 'Blanco',
    'color.Gray': 'Gris',
    'color.Red': 'Rojo',
    'color.Orange': 'Naranja',
    'color.Yellow': 'Amarillo',
    'color.Green': 'Verde',
    'color.Teal': 'Verde azulado',
    'color.Blue': 'Azul',
    'color.Purple': 'Morado',
    'color.Pink': 'Rosa',
    'color.Brown': 'Marrón',
  },
  'fr': {
    'tagline':
        'Aide les personnes daltoniennes à mieux distinguer les couleurs.',
    'onboarding.enhance.title': 'Renforcer les différences',
    'onboarding.enhance.text':
        'Appliquez des filtres lorsque les couleurs sont difficiles à distinguer.',
    'onboarding.identify.title': 'Identifier les couleurs',
    'onboarding.identify.text':
        'Utilisez la caméra pour voir le nom et le code hexadécimal en temps réel.',
    'onboarding.understand.title': 'Comprendre la vision des couleurs',
    'onboarding.understand.text':
        'Prévisualisez des simulations des différences de vision des couleurs.',
    'getStarted': 'Commencer',
    'tab.assist': 'Aide',
    'tab.detect': 'Détecter',
    'tab.simulate': 'Simuler',
    'tab.settings': 'Réglages',
    'appearance': 'Apparence',
    'darkMode': 'Mode sombre',
    'darkEnabled': 'Thème sombre activé',
    'lightEnabled': 'Thème clair activé',
    'language': 'Langue',
    'legal': 'Mentions légales',
    'privacyPolicy': 'Politique de confidentialité',
    'termsOfUse': "Conditions d'utilisation",
    'about': 'À propos',
    'appName': "Nom de l'app",
    'appVersion': "Version de l'app",
    'linkError': "Impossible d'ouvrir le lien. Réessayez.",
    'original': 'Original',
    'assistFilters': "Filtres d'aide",
    'takePhoto': 'Prendre une photo',
    'uploadPhoto': 'Importer une photo',
    'reset': 'Réinitialiser',
    'normal': 'Normal',
    'startingCamera': 'Démarrage de la caméra...',
    'cameraUnavailable': 'Caméra indisponible. Vérifiez les autorisations.',
    'color.Black': 'Noir',
    'color.White': 'Blanc',
    'color.Gray': 'Gris',
    'color.Red': 'Rouge',
    'color.Orange': 'Orange',
    'color.Yellow': 'Jaune',
    'color.Green': 'Vert',
    'color.Teal': 'Turquoise',
    'color.Blue': 'Bleu',
    'color.Purple': 'Violet',
    'color.Pink': 'Rose',
    'color.Brown': 'Marron',
  },
  'it': {
    'tagline': 'Aiuta le persone daltoniche a distinguere meglio i colori.',
    'onboarding.enhance.title': 'Migliora le differenze di colore',
    'onboarding.enhance.text':
        'Applica filtri di assistenza quando i colori sono difficili da distinguere.',
    'onboarding.identify.title': 'Identifica i colori intorno a te',
    'onboarding.identify.text':
        'Usa la fotocamera per vedere nome e codice esadecimale in tempo reale.',
    'onboarding.understand.title': 'Comprendi la visione dei colori',
    'onboarding.understand.text':
        'Visualizza simulazioni delle differenze nella percezione dei colori.',
    'getStarted': 'Inizia',
    'tab.assist': 'Assistenza',
    'tab.detect': 'Rileva',
    'tab.simulate': 'Simula',
    'tab.settings': 'Impostazioni',
    'appearance': 'Aspetto',
    'darkMode': 'Modalità scura',
    'darkEnabled': 'Tema scuro attivo',
    'lightEnabled': 'Tema chiaro attivo',
    'language': 'Lingua',
    'legal': 'Note legali',
    'privacyPolicy': 'Informativa sulla privacy',
    'termsOfUse': "Termini d'uso",
    'about': 'Informazioni',
    'appName': "Nome dell'app",
    'appVersion': "Versione dell'app",
    'linkError': 'Impossibile aprire il link. Riprova.',
    'original': 'Originale',
    'assistFilters': 'Filtri di assistenza',
    'takePhoto': 'Scatta foto',
    'uploadPhoto': 'Carica foto',
    'reset': 'Ripristina',
    'normal': 'Normale',
    'startingCamera': 'Avvio fotocamera...',
    'cameraUnavailable': 'Fotocamera non disponibile. Controlla i permessi.',
    'color.Black': 'Nero',
    'color.White': 'Bianco',
    'color.Gray': 'Grigio',
    'color.Red': 'Rosso',
    'color.Orange': 'Arancione',
    'color.Yellow': 'Giallo',
    'color.Green': 'Verde',
    'color.Teal': 'Verde acqua',
    'color.Blue': 'Blu',
    'color.Purple': 'Viola',
    'color.Pink': 'Rosa',
    'color.Brown': 'Marrone',
  },
  'de': {
    'tagline':
        'Hilft Menschen mit Farbsehschwäche, Farben besser zu unterscheiden.',
    'onboarding.enhance.title': 'Farbunterschiede verstärken',
    'onboarding.enhance.text':
        'Wenden Sie Hilfsfilter an, wenn Farben schwer zu unterscheiden sind.',
    'onboarding.identify.title': 'Farben in der Umgebung erkennen',
    'onboarding.identify.text':
        'Prüfen Sie Farbname und Hex-Code live mit der Kamera.',
    'onboarding.understand.title': 'Farbsehen verstehen',
    'onboarding.understand.text':
        'Sehen Sie Simulationen verschiedener Farbwahrnehmungen an.',
    'getStarted': 'Loslegen',
    'tab.assist': 'Hilfe',
    'tab.detect': 'Erkennen',
    'tab.simulate': 'Simulieren',
    'tab.settings': 'Einstellungen',
    'appearance': 'Darstellung',
    'darkMode': 'Dunkelmodus',
    'darkEnabled': 'Dunkles Design aktiviert',
    'lightEnabled': 'Helles Design aktiviert',
    'language': 'Sprache',
    'legal': 'Rechtliches',
    'privacyPolicy': 'Datenschutzrichtlinie',
    'termsOfUse': 'Nutzungsbedingungen',
    'about': 'Info',
    'appName': 'App-Name',
    'appVersion': 'App-Version',
    'linkError': 'Link kann nicht geöffnet werden. Bitte erneut versuchen.',
    'original': 'Original',
    'assistFilters': 'Hilfsfilter',
    'takePhoto': 'Foto aufnehmen',
    'uploadPhoto': 'Foto hochladen',
    'reset': 'Zurücksetzen',
    'normal': 'Normal',
    'startingCamera': 'Kamera wird gestartet...',
    'cameraUnavailable': 'Kamera nicht verfügbar. Prüfen Sie die Berechtigung.',
    'color.Black': 'Schwarz',
    'color.White': 'Weiß',
    'color.Gray': 'Grau',
    'color.Red': 'Rot',
    'color.Orange': 'Orange',
    'color.Yellow': 'Gelb',
    'color.Green': 'Grün',
    'color.Teal': 'Blaugrün',
    'color.Blue': 'Blau',
    'color.Purple': 'Lila',
    'color.Pink': 'Rosa',
    'color.Brown': 'Braun',
  },
};
